### ISSUE TITLE
dev chain transaction mined, but web3 receipt has status: false

### ISSUE THREAD

**Issue by dforsten** [paritytech/pwasm-tutorial#40]
Starting the dev chain using parity v2.0.8-stable.
Contract step-5 compile and deploy as described in the README without problems.

I get an error message after issuing this line in node though:
```
web3.eth.personal.unlockAccount(web3.eth.defaultAccount, "user").then(() => TokenContract.methods.transfer("0x7BA4324585CB5597adC283024819254345CD7C62", 200).send()).then(console.log).catch(console.log);
```

The transaction gets mined, and the transfer is successful. Checking the balance of the target address returns "200" as expected, using the following command:
```
TokenContract.methods.balanceOf("0x7BA4324585CB5597adC283024819254345CD7C62").call().then(console.log).catch(console.log);
```

The reason for the failure web3 reports("Error: Transaction has been reverted by the EVM") seems to be that the JSON receipt has "status" set to "false":

```
...
  "root": null,
  "status": false,
  "to": "0xedfc9c2f4cfa7495c1a95cfe1cb856f5980d5e18",
...
```

This is an issue for using/testing contracts using web3, since transactions which actually seem to have succeeded are reported as failed.

**Comment by dforsten** [comment]
Full error message:
```
Address of new contract: 0xc49df43D87d6227D3d6D84d590514B6cf6f79712
Trying to transfer 200 credits
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x3d6c864a6ee1d33dfd0b1310ae906766f061d98cecfab4fea070e009e45dbf4f",
  "blockNumber": 34,
  "contractAddress": null,
  "cumulativeGasUsed": 61051,
  "from": "0x004ec07d2329997267ec62b4166639513386f32e",
  "gasUsed": 61051,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000008000000000000000000000000000000000008000000000000000000000000000000000000000000010000000000000000004000000000000000000000000000000010000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000082000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000010000000000000000000000000",
  "root": null,
  "status": false,
  "to": "0xc49df43d87d6227d3d6d84d590514b6cf6f79712",
  "transactionHash": "0xe01324efd1f883321b57c88e4a309d786fc724c752e2c9c5ee86e3d792c3a38d",
  "transactionIndex": 0,
  "events": {
    "Transfer": {
      "address": "0xc49df43D87d6227D3d6D84d590514B6cf6f79712",
      "blockHash": "0x3d6c864a6ee1d33dfd0b1310ae906766f061d98cecfab4fea070e009e45dbf4f",
      "blockNumber": 34,
      "logIndex": 0,
      "removed": false,
      "transactionHash": "0xe01324efd1f883321b57c88e4a309d786fc724c752e2c9c5ee86e3d792c3a38d",
      "transactionIndex": 0,
      "transactionLogIndex": "0x0",
      "type": "mined",
      "id": "log_768c4368",
      "returnValues": {
        "0": "0x004ec07d2329997267Ec62b4166639513386F32E",
        "1": "0x7BA4324585CB5597adC283024819254345CD7C62",
        "2": "200",
        "indexed_from": "0x004ec07d2329997267Ec62b4166639513386F32E",
        "indexed_to": "0x7BA4324585CB5597adC283024819254345CD7C62",
        "_value": "200"
      },
      "event": "Transfer",
      "signature": "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
      "raw": {
        "data": "0x00000000000000000000000000000000000000000000000000000000000000c8",
        "topics": [
          "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
          "0x000000000000000000000000004ec07d2329997267ec62b4166639513386f32e",
          "0x0000000000000000000000007ba4324585cb5597adc283024819254345cd7c62"
        ]
      }
    }
  }
}
    at /Users/davidf/branches/pwasm-streem/node_modules/web3-core-method/src/index.js:364:46
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by d10r** [comment]
The chain spec used does probably not include `eip658Transition` in section `params`. That's needed because the default (pre-Metropolis) config doesn't have a status field for receipts.
Docs: https://wiki.parity.io/Chain-specification

**Comment by dforsten** [comment]
Works like a charm with that modification to the chain spec, thanks Didi! :-)

**Comment by fckt** [comment]
> The chain spec used does probably not include `eip658Transition` in section `params`. That's needed because the default (pre-Metropolis) config doesn't have a status field for receipts.
> Docs: https://wiki.parity.io/Chain-specification

Thanks for the notice! We have to add this into params, for sure!
