### ISSUE TITLE
Tutorial can't be passed from scratch

### ISSUE THREAD

**Issue by NikVolf** [paritytech/pwasm-tutorial#8]
```
Error: Cannot find module 'web3'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/admin/git/pwasm-tutorial/deploy.js:1:74)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by juniorvid** [comment]
I believe you have to install the web3 package globally with ``npm install -g web3``

**Comment by NikVolf** [comment]
Aye, did it but still get this error

**Comment by juniorvid** [comment]
Maybe you can try adding it locally as well?

**Comment by fckt** [comment]
just tried. `npm install -g web3` works for me..

**Comment by chevdor** [comment]
Also having issues. The building part is smooth.
When it comes to deploying, I solved the missing web3 problem by installing it locally (no need for web3 globally):
```
npm init
npm i --save-dev web3 
```

That allows passing the web3 issue mentioned in this issue.

**Comment by fckt** [comment]
I've added `package.json` to the repo, so now it's possible to run `npm install` and use the local `web3.js`
